### ISSUE TITLE
Array Buffer Allocation Failed

### ISSUE THREAD

**Issue by andrewfitz** [TheMorpheus407/OpenAI-Audiobook-Generator#7]
Hi, I appreciate your work here, though I am real bummed I have lost $100+ through OpenAi because this spent hours calling the API, but fails to combine at the end and I lose everything. I have used this on a Mac and PC with 64GB of RAM.

All works fine for small requests, but large requests for 100k, 400k, chars etc it fails at the end with nothing to show for it, and I've lost money. It seems to call the API right, but errors out when merging. It is a not a system memory issue.

And it seems none of the data was saved from the API calls so I can't even recover and manually merge the wav files. Can you store the data into a data store or something that can be recovered if this happens or have some safe fallback so it's not all wasted? Any way to make this work with very high char counts?

Thank you.

`main.js:34 Uncaught (in promise) RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at concatenateWAVBuffers (main.js:34:32)
    at mergeAudioBlobsAndDownload (main.js:18:29)`

**Comment by GodGardensGuns** [comment]
This just happened to me. Same exact error. Thankfully, I only lost $5, but it was still inconvenient after waiting for an hour. It also shows how little text is required to trigger this error. This was for about 300k characters.
